### ISSUE TITLE
Getting an error when the sonar scanner runs

### ISSUE THREAD

**Issue by MahendraPalagiri** [nosinovacao/dotnet-sonar#16]
I have downloaded the latest version from docker hub and trying to run in my project (building the docker image on a linux machine)

Getting error attached could someone help
![A633BBCD-2ED6-48A8-B901-9461069C7C4B](https://user-images.githubusercontent.com/48267163/76496270-acfa2700-645e-11ea-942d-6e72052fe3ae.jpeg)

**Comment by gafda** [comment]
Hi there!

Reading your stack-trace, the error you reported looks like something to do with a miss-configured plugin you installed in your SonarQube server called **_Sonargraph Integration_**.

If after you review your settings the same problem continues, I suggest opening an issue in their plugin site:

https://github.com/sonargraph/sonar-sonargraph-integration/issues
