### ISSUE TITLE
Docker hub

### ISSUE THREAD

**Issue by Tantol** [nosinovacao/dotnet-sonar#22]
Hello,
on the start: Thank you for this awesome image it helps a lot.

Can I ask you to update builds on docker hub (https://hub.docker.com/r/nosinovacao/dotnet-sonar/tags)?

**Comment by jaimesantosferreira** [comment]
Hello!

All the images are in the GitHub Container Registry (ghcr.io), and are public. Is there any reason why you cannot get them from there?

**Comment by Tantol** [comment]
I didn't know about this source. Now when I know all good. Thank you.
