### ISSUE TITLE
23.02.3 and 23.02.4 are the wrong way around

### ISSUE THREAD

**Issue by xsacha** [nosinovacao/dotnet-sonar#24]
The 23.02.4 is actually dotnet 6: https://github.com/nosinovacao/dotnet-sonar/blob/23.02.4/Dockerfile
23.02.3 is dotnet 7: https://github.com/nosinovacao/dotnet-sonar/blob/23.02.3/Dockerfile

The docker image is correct but the tags don't appear to be.

**Comment by jaimesantosferreira** [comment]
Hello, and thank you very much for the remark. We've just uploaded updated images, and the tags should be correct, now.
