### ISSUE TITLE
Sonar is ceasing support of Java 11 on October 31 -- Upgrade to Java 17

### ISSUE THREAD

**Issue by craigbehnke** [nosinovacao/dotnet-sonar#25]
Sonar will be retiring the Java 11 runtime on October 31st, 2023. [(announcement)](https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597?_gl=1*h5ydfk*_gcl_au*MTMwODU3MzgwMS4xNjkxMzk1MTYz*_ga*MjA5ODA1NzkxNS4xNjc2NDE3NjM5*_ga_9JZ0GZ5TC6*MTY5MTQ0NzA4OS40MS4xLjE2OTE0NTAyMzUuNTcuMC4w) [(docs)](https://docs.sonarcloud.io/appendices/scanner-environment/)

Since it looks like this image uses Java 11, the dockerfile should be updated before then.

Warning log I'm seeing in job execution:
`WARN: The version of Java (11.0.18) you have used to run this analysis is deprecated and we will stop accepting it soon. Please update to at least Java 17.`

Image version I'm using: `23.06.3`

**Comment by jaimesantosferreira** [comment]
Hello!

Thank you very much for the heads up on that matter. Both .NET 6 and .NET 7 images have just been updated, and are now using Java 17 runtime.

Best regards,
Jaime

**Comment by craigbehnke** [comment]
Thank you very much!
