### ISSUE TITLE
Current versioning system does not work well with automated dependency upgrade managers

### ISSUE THREAD

**Issue by craigbehnke** [nosinovacao/dotnet-sonar#31]
With the current CalVer system for versioning the generated images, a breaking change can be experienced by upgrading from the lowest to highest patch version.

Everyone who uses this image likely knows why this is (different dotnet versions) and can refrain from upgrading this image, but automated tools that upgrade dependencies for projects, such as [renovate](https://github.com/renovatebot/renovate), do not know about this limitation and therefore mistakenly upgrade. This upgrade is often done as one upgrade among several, which also breaks the other upgrades.

### Suggested Solution

Do not control for the dotnet version within the image versioning scheme, but rather append a version suffix when publishing the image (so 23.12.3 -> 23.12.0-dotnet6, 23.12.4 -> 23.12.0-dotnet7, 23.12.5 -> 23.12.0-dotnet8)

Making this change would be **greatly** appreciated, since every automated dependency update made on my server code repository has been foiled by this versioning issue.

**Comment by jaimesantosferreira** [comment]
Hello!

We've just uploaded new images for .NET6, .NET7 and .NET8, and added new tags on each one of them, based upon your suggestions. Therefore, you'll now be able to use:

24.01-dotnet6 for .NET6 image;
24.01-dotnet7 for .NET7 image;
24.01-dotnet8 for .NET8 image.

Hope this works! All the best,
Jaime

**Comment by craigbehnke** [comment]
Thank you very much!!!
