### ISSUE TITLE
4.4.1/4.3.1 Error in dotnet sonarscanner end 

### ISSUE THREAD

**Issue by staticdev** [nosinovacao/dotnet-sonar#5]
I have followed the instructions in here: https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+MSBuild

And when I execute: 'dotnet sonarscanner end'

I get the following output:
`SonarScanner for MSBuild 4.3.1

Using the .NET Core version of the Scanner for MSBuild

Default properties file was found at /opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.3.1/dotnet-sonarscanner/4.3.1/tools/netcoreapp2.1/any/SonarQube.Analysis.xml

Loading analysis properties from /opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.3.1/dotnet-sonarscanner/4.3.1/tools/netcoreapp2.1/any/SonarQube.Analysis.xml

Post-processing started.

11:15:10.274  Loading the SonarQube analysis config from /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/conf/SonarQubeAnalysisConfig.xml

11:15:10.302  Not running under TeamBuild

11:15:10.303  Analysis base directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube

Build directory: 

Bin directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/bin

Config directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/conf

Output directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/out

Config file: /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/conf/SonarQubeAnalysisConfig.xml

Generating SonarQube project properties file to /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/out/sonar-project.properties

Setting analysis property: sonar.visualstudio.enable=false

The supplied Code Analysis ErrorLog file is a valid json file and does not need to be fixed: /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/dist/APISN.Webservices.Opcao.dll.RoslynCA.json

Using longest common projects root path as project base directory: '/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao'.

Dumping content of sonar-project.properties

------------------------------------------------------------------------

sonar.projectKey=DEBHE.DE605.APISN.Webservices.Opcao

sonar.projectName=DEBHE.DE605.APISN.Webservices.Opcao

sonar.projectVersion=0.0.1

sonar.working.directory=/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/out/.sonar

sonar.projectBaseDir=/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.projectKey=DEBHE.DE605.APISN.Webservices.Opcao:C78B51AA-1311-4EFE-BDB7-5FE10BEE452E

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.projectName=APISN.Webservices.Opcao

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.projectBaseDir=/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.sourceEncoding=utf-8

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.sources=\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Authentication/JwtTokenConfiguration.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Controllers/OpcaoController.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Helpers/HttpHelper.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Models/Erro.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Models/OpcaoSn.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Models/PeriodoMei.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Models/PeriodoSimples.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Program.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Startup.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/obj/Release/netcoreapp2.1/APISN.Webservices.Opcao.RazorAssemblyInfo.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/obj/Release/netcoreapp2.1/APISN.Webservices.Opcao.AssemblyInfo.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/nuget.config",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/appsettings.Development.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/appsettings.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/APISN.Webservices.Opcao/Properties/launchSettings.json"

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.cs.roslyn.reportFilePath=/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/dist/APISN.Webservices.Opcao.dll.RoslynCA.json

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.cs.analyzer.projectOutPath=/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/out/0

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.cs.analyzer.projectOutPaths=\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/out/0"

C78B51AA-1311-4EFE-BDB7-5FE10BEE452E.sonar.cs.roslyn.reportFilePaths=\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/src/dist/APISN.Webservices.Opcao.dll.RoslynCA.json"

sonar.host.url=http://sonar.aic.serpro:8080

sonar.cs.vstest.reportsPaths=%CD%TestResults*.trx

sonar.cs.vscoveragexml.reportsPaths=%CD%VisualStudio.coveragexml

sonar.buildbreaker.queryMaxAttempts=60

sonar.verbose=true

sonar.exclusions=**/*.css,**/*.js,**/*.xhtml,**/*.xml

sonar.visualstudio.enable=false

sonar.modules=C78B51AA-1311-4EFE-BDB7-5FE10BEE452E

------------------------------------------------------------------------

Writing processing summary to /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/out/ProjectInfo.log

SONAR_SCANNER_OPTS is not configured. Setting it to the default value of -Xmx1024m

Calling the SonarQube Scanner...

Setting environment variable 'SONAR_SCANNER_OPTS'. Value: -Xmx1024m

Executing file /opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.3.1/dotnet-sonarscanner/4.3.1/tools/netcoreapp2.1/any/sonar-scanner-3.2.0.1227/bin/sonar-scanner

  Args: -Dsonar.scanAllFiles=true -Dproject.settings=/opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore/.sonarqube/out/sonar-project.properties --embedded <sensitive data removed>

  Working directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/NetCore

  Timeout (ms):-1

  Process id: 28083

which: no java in (/usr/local/bin:/usr/bin:/opt/programas/jenkins2/.dotnet/tools:/opt/programas/jenkins2/bin)

/opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.3.1/dotnet-sonarscanner/4.3.1/tools/netcoreapp2.1/any/sonar-scanner-3.2.0.1227/bin/sonar-scanner: line 59: exec: : not found

Process returned exit code 127

The SonarQube Scanner did not complete successfully

11:15:10.647  Creating a summary markdown file...

11:15:10.65  Post-processing failed. Exit code: 1

script returned exit code 1`

**Comment by staticdev** [comment]
I have updated the scanner to version 4.4.1, but the error still occurs:

`SonarScanner for MSBuild 4.4.1

Using the .NET Core version of the Scanner for MSBuild

Default properties file was found at /opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.4.1/dotnet-sonarscanner/4.4.1/tools/netcoreapp2.1/any/SonarQube.Analysis.xml

Loading analysis properties from /opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.4.1/dotnet-sonarscanner/4.4.1/tools/netcoreapp2.1/any/SonarQube.Analysis.xml

Post-processing started.

10:15:40.376  Loading the SonarQube analysis config from /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/conf/SonarQubeAnalysisConfig.xml

10:15:40.404  Not running under TeamBuild

10:15:40.405  Analysis base directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube

Build directory: 

Bin directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/bin

Config directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/conf

Output directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/out

Config file: /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/conf/SonarQubeAnalysisConfig.xml

Generating SonarQube project properties file to /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/out/sonar-project.properties

Setting analysis property: sonar.visualstudio.enable=false

The supplied Code Analysis ErrorLog file is a valid json file and does not need to be fixed: /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/dist/APISN.Web.Token.dll.RoslynCA.json

Using longest common projects root path as project base directory: '/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token'.

Dumping content of sonar-project.properties

------------------------------------------------------------------------

sonar.projectKey=DEBHE.DE605.APISN.Web.Token

sonar.projectName=DEBHE.DE605.APISN.Web.Token

sonar.projectVersion=0.0.1

sonar.working.directory=/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/out/.sonar

sonar.projectBaseDir=/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token


E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.projectKey=DEBHE.DE605.APISN.Web.Token:E4CE25A8-2F0F-44B5-B164-87C0F0F748F4

E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.projectName=APISN.Web.Token

E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.projectBaseDir=/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token

E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.sourceEncoding=utf-8

E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.sources=\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Controllers/PedidoAcessoController.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Models/DBD_11127_APISNContext.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Models/ErrorViewModel.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Models/HistoricoPedidoAcesso.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Models/PedidoAcesso.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Models/Sistema.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Program.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Startup.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Util/EnumSistema.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Util/UtilSistema.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/obj/Release/netcoreapp2.1/APISN.Web.Token.RazorAssemblyInfo.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/obj/Release/netcoreapp2.1/APISN.Web.Token.AssemblyInfo.cs",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/PedidoAcesso/Create.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/PedidoAcesso/Delete.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/PedidoAcesso/Details.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/PedidoAcesso/Edit.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/PedidoAcesso/Index.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/Shared/Error.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/Shared/_CookieConsentPartial.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/Shared/_Layout.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/Shared/_ValidationScriptsPartial.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/_ViewImports.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Views/_ViewStart.cshtml",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/css/site.css",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/css/site.min.css",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/favicon.ico",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/images/banner1.svg",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/images/banner2.svg",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/images/banner3.svg",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/js/site.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/js/site.min.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/.bower.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.css.map",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap-theme.min.css.map",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap.css",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap.css.map",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/css/bootstrap.min.css.map",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.eot",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.svg",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/js/bootstrap.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/js/bootstrap.min.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/dist/js/npm.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/bootstrap/LICENSE",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation-unobtrusive/.bower.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation-unobtrusive/LICENSE.txt",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation/.bower.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation/dist/additional-methods.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation/dist/additional-methods.min.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation/dist/jquery.validate.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation/dist/jquery.validate.min.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery-validation/LICENSE.md",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery/.bower.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery/dist/jquery.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery/dist/jquery.min.js",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery/dist/jquery.min.map",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/wwwroot/lib/jquery/LICENSE.txt",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/appsettings.Development.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/appsettings.json",\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/APISN.Web.Token/Properties/launchSettings.json"


E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.cs.roslyn.reportFilePath=/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/dist/APISN.Web.Token.dll.RoslynCA.json

E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.cs.analyzer.projectOutPath=/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/out/0

E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.cs.analyzer.projectOutPaths=\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/out/0"

E4CE25A8-2F0F-44B5-B164-87C0F0F748F4.sonar.cs.roslyn.reportFilePaths=\

"/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/src/dist/APISN.Web.Token.dll.RoslynCA.json"


sonar.host.url=http://sonar.aic.serpro:8080

sonar.cs.vstest.reportsPaths=%CD%TestResults*.trx

sonar.cs.vscoveragexml.reportsPaths=%CD%VisualStudio.coveragexml

sonar.buildbreaker.queryMaxAttempts=60

sonar.exclusions=**/*.css,**/*.js,**/*.xhtml,**/*.xml

sonar.visualstudio.enable=false


sonar.modules=E4CE25A8-2F0F-44B5-B164-87C0F0F748F4



------------------------------------------------------------------------

Writing processing summary to /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/out/ProjectInfo.log

SONAR_SCANNER_OPTS is not configured. Setting it to the default value of -Xmx1024m

Calling the SonarQube Scanner...

Setting environment variable 'SONAR_SCANNER_OPTS'. Value: -Xmx1024m

Executing file /opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.4.1/dotnet-sonarscanner/4.4.1/tools/netcoreapp2.1/any/sonar-scanner-3.2.0.1227/bin/sonar-scanner

  Args: -Dsonar.scanAllFiles=true -Dproject.settings=/opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token/.sonarqube/out/sonar-project.properties --embedded --debug <sensitive data removed>

  Working directory: /opt/programas/jenkins2/workspace/DEBHE/DE605/APISN.Web.Token

  Timeout (ms):-1

  Process id: 11159

which: no java in (/usr/local/bin:/usr/bin:/opt/programas/jenkins2/.dotnet/tools:/opt/programas/jenkins2/bin)

/opt/programas/jenkins2/.dotnet/tools/.store/dotnet-sonarscanner/4.4.1/dotnet-sonarscanner/4.4.1/tools/netcoreapp2.1/any/sonar-scanner-3.2.0.1227/bin/sonar-scanner: line 59: exec: : not found

Process returned exit code 127

The SonarQube Scanner did not complete successfully

10:15:40.665  Creating a summary markdown file...

10:15:40.667  Post-processing failed. Exit code: 1

script returned exit code 1`

**Comment by staticdev** [comment]
Pull request #6 updates to version to 4.4.2 to fix the problem.

**Comment by calexandre** [comment]
Okay thank you @staticdev . Well test it out on our end, and if everything goes smoothly, we'll merge the PR!

**Comment by calexandre** [comment]
Fixed on #6 and #7
