### ISSUE TITLE
What License is this under?

### ISSUE THREAD

**Issue by philipstaffordwood** [nosinovacao/dotnet-sonar#8]
Hi,

Nice `Dockerfile`.
I'm a member of a team finding it useful in our c# build pipeline.
We've found previous issues with handy `Dockerfile`'s that end up having inappropriate licenses.

**Could you please make your License for this explicit?**

**Comment by calexandre** [comment]
Thank you!
You are totally right.

We have updated our master branch with license.

**Comment by philipstaffordwood** [comment]
Thanks!

Much appreciated,

Obrigados
and
desejar felicidades
Kind Regards

<https://bvnk.co/> *Philip Wood*
DevOps Engineer
philip@bvnk.co

BVNK LTD
https://bvnk.co
